version: '3.8'

services:
  jenkins:
    build: ./jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elk
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1

volumes:
  jenkins_data:

networks:
  elk:
    external: true
    name: elk-post_elk
